version: "3.8"
services:
  redis:
    image: "redis:alpine"
    ports:
    - "6379:6379"
  elastic:
    image: "elasticsearch:7.9.3"
    ports:
    - "9200:9200"
    environment:
      discovery.type: single-node
  minio:
    image: "minio/minio"
    environment:
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: password
    command: server /data
    ports:
    - "9000:9000"
  couchdb:
    build: ./couchdb
    environment:
      COUCHDB_USER: "admin"
      COUCHDB_PASSWORD: "password"
    ports:
    - "5984:5984"


