name: Publish Test Image
on:
  push:
    branches:
      - main
    paths:
      - "images/test/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
          registry-url: "https://registry.npmjs.org"
          scope: "@hyper.io"
      - run: cd images/test && yarn
      - run: cd images/test && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
