
name: publish nodejs client 

on: 
  push:
    tags:
      - 'nodejs-client@*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
          registry-url: "https://registry.npmjs.org"
          scope: "@hyper63"
      - run: cd packages/nodejs-client && yarn
      - run: cd packages/nodejs-client && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
