name: Publish Port Data
on:
  push:
    branches:
      - main
    paths:
      - "packages/port-data/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
          registry-url: "https://registry.npmjs.org"
          scope: "@hyper63"
      - run: cd packages/port-data && yarn
      - run: cd packages/port-data && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
