name: test core
on:
  push:
    branches-ignore: main
    paths:
      - "packages/core/**"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno: [1.11.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Deno ${{ matrix.deno }}
        uses: denolib/setup-deno@master
        with:
          deno-version: ${{ matrix.deno }}
      - run: cd packages/core && ./scripts/test.sh
        env:
          CI: true
