name: test bee-queue adapter
on:
  push:
    branches-ignore: main
    paths:
      - "packages/adapter-beequeue/**"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: cd packages/adapter-beequeue && yarn
      - run: cd packages/adapter-beequeue && yarn test
        env:
          CI: true
