name: test core
on:
  push:
    tags-ignore: '*'
    branches:
      - main
      - '**'
    paths:
      - "packages/core/**"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno: [1.12.2]
    steps:
      - uses: actions/checkout@v2
      - name: Use Deno ${{ matrix.deno-version }}
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}
      - run: cd packages/core && ./scripts/test.sh
        env:
          CI: true
