name: test connect
on:
  push:
    branches:
      - "**"
    paths:
      - "packages/connect/**"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno-version: [1.14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Deno ${{ matrix.deno-version }}
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}
      - run: cd packages/connect && ./scripts/test.sh
        env:
          CI: true
