name: test image cloud-dev
on:
  push:
    branches:
      - "**"
    paths:
      - "images/cloud-dev/**"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno-version: [1.13.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Deno ${{ matrix.deno-version }}
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}
      - run: cd images/cloud-dev && ./scripts/test.sh
        env:
          CI: true
